### ISSUE TITLE
Segmentation fault in pagekite_thread_start processing

### ISSUE THREAD

**Issue by eldiener** [pagekite/libpagekite#60] opened 2018-06-18 14:40 UTC
I am using libpagekite with ir manager v0.91.171102C

After calling the 'pagekite_thread_start' function while debugging under gdb, I am seeing a segmentation fault in one of the libpagekite threads. The gdb information gives me:

```
Thread 6 "myprogram" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x742fe440 (LWP 1118)]
0x76a48842 in pk_connect_ai (pkc=0x74e7f6f8, ai=0x74e7f6d8, reconnecting=0, n=4, requests=0x702e7d3b, session_id=0x6674726f <error: Cannot access memory at address 0x6674726f>, ctx=0x6f696c6f,
    hostname=0x2076616e <error: Cannot access memory at address 0x2076616e>) at pkproto.c:754
754         requests[i].status = PK_KITE_FLYING;
```

The pagekite messages leading up to this segmentation fault are:

```
t=2018-06-18 10:08:29.448; ts=5b27bcdd; tid=742fe440; ll=3; msg=No front-end wanted, randomly using some.url (status=1000080)
t=2018-06-18 10:08:29.448; ts=5b27bcdd; tid=742fe440; ll=4; msg=Connecting to [nnn.nnn.nnn.nnn]:ppp (session=new)
t=2018-06-18 10:08:29.558; ts=5b27bcdd; tid=742fe440; ll=5; msg=8: TLSv1.2 connection established: ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH Au=RSA Enc=AESGCM(256) Mac=AEAD
t=2018-06-18 10:08:31.562; ts=5b27bcdf; tid=742fe440; ll=6; msg=Connect failed: 8
t=2018-06-18 10:08:31.562; ts=5b27bcdf; tid=742fe440; ll=7; msg=pkmanager.c: Connection error -30002
t=2018-06-18 10:08:43.331; ts=5b27bceb; tid=74aff440; ll=8; msg=Tick!  [repeating=yes, next=16, tunnels=0, v=0.91.171102C]
t=2018-06-18 10:08:59.347; ts=5b27bcfb; tid=74aff440; ll=9; msg=Tick!  [repeating=yes, next=21, tunnels=0, v=0.91.171102C]
t=2018-06-18 10:08:59.592; ts=5b27bcfb; tid=742fe440; ll=a; msg=No front-end wanted, randomly using some.url (status=1000080)
t=2018-06-18 10:08:59.593; ts=5b27bcfb; tid=742fe440; ll=b; msg=Connecting to [nnn.nnn.nnn.nnn]:ppp (session=new)
t=2018-06-18 10:08:59.692; ts=5b27bcfb; tid=742fe440; ll=c; msg=8: TLSv1.2 connection established: ECDHE-RSA-AES256-GCM-SHA384 TLSv1.2 Kx=ECDH Au=RSA Enc=AESGCM(256) Mac=AEAD

```

I have disguised the url, as 'some.url' and ip address, as 'nnn.nnn.nnn.nnn:ppp' for security reasons.

Is this a known problem ?

The code calls 'pagekite_init', 'pagekite_lookup_and_add_frontend', and 'pagekite_add_kite' successfully before calling 'pagekite_thread_start' successfully. While it is possible that the frontend and the kite may not be configured correctly, I do not think a segmentation fauilt should occur in code. If this is a known problem which has been fixed I will get the latest libpagekite and build again.

**Comment by BjarniRunar** [comment] 2018-06-20 14:08
Please always test against the latest libpagekite. This is not a known issue.

Since I know from our previous discussions that you are (or were) running `pagekite_thread_start` more than once, if this is happening on the second invocation than this is pretty much expected behaviour. After `pagekite_thread_stop` the internal state of the library is not sane and things must be reconfigured from scratch.

**Comment by eldiener** [comment] 2018-06-21 21:47
I have subsequently tested with the latest pagekite and the problem still exists. I can narrow down the problem in my test by saying that the frontend URL is incorrect when I call 'pagekite_lookup_and_add_frontend' to setup the frontend before calling 'pagekite_thread_start', during whose processing the segmentation fault occurs even though the actual call to 'pagekite_thread_start' returns successfully. Furthermore this is the first time 'pagekite_thread_start' has been called, and it is not part of any cycle of calling 'page_thread_start/pagekite_thread_stop' more than once, which I do understand libpagekite does not support. When I do pass the correct frontend URL to 'pagekite_lookup_and_add_frontend' before calling 'pagekite_thread_start' the crash does not occur and libpagekite works correctly. The actual difference between the incorrect and correct frontend URL in my case is the difference between passing an incorrect URL of 'some.url' instead of the correct URL of 'someprefix.some.url'.

I realize that passing an incorrect URL should naturally mean that pagekite does not connect my local backend URL to the Internet frontend URL, and I can accept that as a result as my own end-user programmer error. But I am sure that from a programming point of view libpagekite crashing as a result with a segmentation fault is not acceptable behavior even in that case. I can understand that it might be very difficult to duplicate this crash without all the exact URL details for backend and frontend, which I can not give due to privacy concerns, but perhaps the gdb information on where the error is occurring might enable this bug to be fixed. My attempt at issuing command 'bt' for a backtrace when this crash occurs under gdb unforunately gives:

Backtrace stopped: previous frame identical to this frame (corrupt stack?)

from gdb.

**Comment by BjarniRunar** [comment] 2018-06-21 23:36
Thank you for providing more details. It sounds like libpagekite is misbehaving badly if the frontend list is empty or bogus. I agree this should be fixed.

I'll take a look next time I context-switch back to libpagekite dev work.

**Comment by BjarniRunar** [comment] 2022-10-11 14:15
I've reviewed the code and am unable to reproduce this. I don't actually see how this can happen, without running pkm_manager_free() from one thread, while another thread is still running the manager.

It's been a while though, the code may simply have changed in the meantime. Sorry this turned out to be a dead end!

**Closed by BjarniRunar** 2022-10-11 14:15 UTC
